#!/bin/bash

## Entries are stored into a directory per month, i.e.
##
##  $DOKUWIKI_ROOT
##  `-- data
##      `-- pages
##          `-- blog                      ..........  var_dirPages
##              `-- YYYY                  ..........  var_dirYear
##                  |-- YYYY-01           ..........  var_dirMonth
##                  |-- YYYY-02
##                  |-- january_YYYY.txt
##                  |-- february_YYYY.txt
##                  `-- march_YYYY.txt
##
## For each new entry the following actions are taken:
## 
##  1. Check if the folder for the current year exists (YYYY); if not,
##     create the folder.
##  2. Check if the folder for the current month exists (YYYY-MM); if not,
##     create the folder.
##

## ==============================================================================
##
##  Variables
##
## ==============================================================================

varVerbose=no
varEditor=emacs

##____________________________________________________________________
## Date atoms

varMonthName=`date "+%B"`
varYear=`date "+%Y"`
varMonth=`date "+%m"`
varDay=`date "+%d"`
varHour=`date "+%H"`
varMinute=`date "+%M"`
var_second=`date "+%S"`
varDate=`date "+%a, %d. %B %Y"`
varTime=`date +%R`

##____________________________________________________________________
## Date combinations

var_yyyymm=`date "+%Y-%m"`
var_yyyymmdd=`date "+%Y-%m-%d"`
var_hhmm=$varHour-$varMinute

varEntry=$var_yyyymmdd"_"$var_hhmm

## Directories for Webgen
varWebgenRoot=/Users/lars/Sites/larsbaehren.com
varWebgenBlog=$varWebgenRoot/src/pages/blog
## Directories for Dokuwiki
varDokuwikiRoot=/Users/lars/Sites/wiki
varDokuwikiBlog=$varDokuwikiRoot/data/pages/blog

var_dirData=/Users/lars/Sites/wiki/data
var_dirMeta=$var_dirData/meta/blog
var_dirYear=$varDokuwikiBlog/$varYear
var_dirMonth=$var_dirYear/$var_yyyymm
var_fileIndex=$var_dirYear/`date "+%B" | tr A-Z a-z`_$varYear.txt
var_fileEntry=$var_dirMonth/$varEntry.txt
var_fileChanges=`echo $var_fileEntry | sed s/"pages\/blog"/"meta\/blog"/ | sed s/".txt"/".changes"/`
var_pathPage=blog:$varYear:$varYear-$varMonth:$varEntry

## ==============================================================================
##
##  Data summary
##
## ==============================================================================

case $varVerbose in
    yes)
    echo "-- Directory pages  = $varDokuwikiBlog"
    echo "-- Directory meta   = $var_dirMeta"
    echo "-- Directory year   = $var_dirYear"
    echo "-- Directory month  = $var_dirMonth"
    echo "-- File month index = $var_fileIndex"
    echo "-- File entry       = $var_fileEntry"
    echo "-- File changes     = $var_fileChanges"
    echo "-- File wiki path   = $var_pathPage" 
    ;;
    *)
    ;;
esac

## ==============================================================================
##
##  Function definitions
##
## ==============================================================================

##____________________________________________________________________
##                                                 writeHeaderDokuwiki
##
##  Produce the basic skeleton for a new blog entry.
##

writeHeaderDokuwiki ()
{
    varDirMonth=${varYear}-${varMonth}
    varFileEntry=${varEntry}.txt

    ## Check if the directory is there

    if [ -d $varDokuwikiBlog ]
    then
	cd $varDokuwikiBlog
	if [ -d $varYear ]
	then
	    cd $varYear
	    if [ -d $varDirMonth ] 
	    then
		cd $varDirMonth
	    else
		mkdir $varDirMonth
		cd $varDirMonth
	    fi
	else
	    mkdir $varYear
	    cd $varYear
	    mkdir $varDirMonth
	    cd $varDirMonth
	fi
    fi

    echo ""                        >> $var_fileEntry
    echo "===== $varTitle ====="   >> $var_fileEntry
    echo ""                        >> $var_fileEntry
    echo "//$varDate - $varTime//" >> $var_fileEntry
    echo ""                        >> $var_fileEntry
    echo "+++"                     >> $var_fileEntry
    echo ""                        >> $var_fileEntry
    echo "{{tag>}}"                >> $var_fileEntry
    echo ""                        >> $var_fileEntry
}

##____________________________________________________________________
##                                                   writeHeaderWebgen

writeHeaderWebgen ()
{
    varDirMonth=${varYear}-${varMonth}
    varFileEntry=${varEntry}.page

    ## Check if the directory is there

    if [ -d $varWebgenBlog ]
    then
	cd $varWebgenBlog
	if [ -d $varYear ]
	then
	    cd $varYear
	    if [ -d $varDirMonth ] 
	    then
		cd $varDirMonth
	    else
		mkdir $varDirMonth
		cd $varDirMonth
	    fi
	else
	    mkdir $varYear
	    cd $varYear
	    mkdir $varDirMonth
	    cd $varDirMonth
	fi
    fi

    ## Create the skeleton file for the new blog entry
    
    echo "---"                          > $varFileEntry
    echo "title: $varTitle"            >> $varFileEntry
    echo "in_menu: false"              >> $varFileEntry
    echo "author: Lars Baehren"        >> $varFileEntry
    echo "---"                         >> $varFileEntry
    echo ""                            >> $varFileEntry
    echo "##{title:}##"                >> $varFileEntry
    echo ""                            >> $varFileEntry
    echo "_${varDate} -- ${varTime}_"  >> $varFileEntry
}

## ==============================================================================
##
##  Processing
##
## ==============================================================================

## -----------------------------------------------------------------------------
## Get the title for the entry

printf "[$varDate - $varTime] ? ";
read varTitle

## ... and create skeleton of file for new entry

echo ""
echo " -> Creating new blog entry ..."
echo ""

writeHeaderWebgen
writeHeaderDokuwiki

## Add link to new entry to the index file

echo "  * [[.$var_yyyymm:$varEntry|$varTitle]] ($varDate - $varTime)" >> $var_fileIndex

## open file in editor

$varEditor $var_fileEntry

## -----------------------------------------------------------------------------
## Create the changes file to make the new entry visible to the blog plugin

## check if the directory, to which we want to write the data, exists

if test -d $var_dirMeta/$varYear/$var_yyyymm ; then 
	echo "-- Diectory for metadata found."
else
	mkdir -p $var_dirMeta/$varYear/$var_yyyymm
	chmod a+rw $var_dirMeta/$varYear/$var_yyyymm
fi

##_______________________________________________________________________________
## Post-editing cleanup of the directory; remove backup files created by emacs

chmod a+rw $var_fileEntry
chmod a+rw $var_fileIndex
chmod a+rwx $var_dirMeta/$varYear
chmod a+rwx $var_dirMeta/$varYear/$var_yyyymm
rm -f $varDokuwikiBlog/*~
rm -f $var_dirYear/*~
rm -f $var_dirMonth/*~
