#!/bin/bash

## Entries are stored into a directory per month, i.e.
##
##  $DOKUWIKI_ROOT
##  `-- data
##      `-- pages
##          `-- blog                      ..........  var_dirPages
##              `-- YYYY                  ..........  var_dirYear
##                  |-- YYYY-01           ..........  var_dirMonth
##                  |-- YYYY-02
##                  |-- january_YYYY.txt
##                  |-- february_YYYY.txt
##                  `-- march_YYYY.txt
##
## For each new entry the following actions are taken:
##
##  1. Check if the folder for the current year exists (YYYY); if not,
##     create the folder.
##  2. Check if the folder for the current month exists (YYYY-MM); if not,
##     create the folder.
##

## ==============================================================================
##
##  Variables
##
## ==============================================================================

varVerbose=no
varEditor=emacs

##____________________________________________________________________
## Date atoms

varMonthName=`date "+%B"`
varYear=`date "+%Y"`
varMonth=`date "+%m"`
varDay=`date "+%d"`
varHour=`date "+%H"`
varMinute=`date "+%M"`
var_second=`date "+%S"`
varDate=`date "+%a, %d. %B %Y"`
varTime=`date +%R`

##____________________________________________________________________
## Date combinations

varYearMonth=`date "+%Y-%m"`
varYearMonthDay=`date "+%Y-%m-%d"`
var_hhmm=$varHour-$varMinute

varEntry=$varYearMonthDay"_"$var_hhmm
varFileTemp=${varEntry}.tmp

## Directories for Webgen
varWebgenRoot=/Users/lars/Sites/larsbaehren.com
varWebgenBlog=$varWebgenRoot/src/pages/blog

var_dirMonth=$var_dirYear/$varYearMonth
var_fileIndex=$var_dirYear/`date "+%B" | tr A-Z a-z`_$varYear.txt
var_fileEntry=$var_dirMonth/$varEntry.txt
var_fileChanges=`echo $var_fileEntry | sed s/"pages\/blog"/"meta\/blog"/ | sed s/".txt"/".changes"/`
var_pathPage=blog:$varYear:$varYear-$varMonth:$varEntry

## Output files
varFileWebgen=$varWebgenBlog/$varYear/$varYearMonth/${varEntry}.page

## ==============================================================================
##
##  Data summary
##
## ==============================================================================

case $varVerbose in
    yes)
      echo "-- Directory meta   = $var_dirMeta"
      echo "-- Directory year   = $var_dirYear"
      echo "-- Directory month  = $var_dirMonth"
      echo "-- File month index = $var_fileIndex"
      echo "-- File entry       = $var_fileEntry"
      echo "-- File changes     = $var_fileChanges"
      echo "-- File wiki path   = $var_pathPage"
    ;;
    *)
    ;;
esac

## ==============================================================================
##
##  Function definitions
##
## ==============================================================================

##____________________________________________________________________
##                                                   writeHeaderWebgen

writeHeaderWebgen ()
{
    varDirMonth=${varYear}-${varMonth}
    varFileEntry=${varEntry}.page

    ## Check if the directory is there

    if [ -d $varWebgenBlog ]
    then
	cd $varWebgenBlog
	if [ -d $varYear ]
	then
	    cd $varYear
	    if [ -d $varDirMonth ]
	    then
          cd $varDirMonth
	    else
		mkdir $varDirMonth
		cd $varDirMonth
	    fi
	else
	    mkdir $varYear
	    cd $varYear
	    mkdir $varDirMonth
	    cd $varDirMonth
	fi
    fi

    ## Create the skeleton file for the new blog entry

    echo "---"                          > $varFileEntry
    echo "title: \"$varTitle\""        >> $varFileEntry
    echo "in_menu: false"              >> $varFileEntry
    echo "author: \"Lars Baehren\""    >> $varFileEntry
    echo "---"                         >> $varFileEntry
    echo ""                            >> $varFileEntry
    echo "##{title:}##"                >> $varFileEntry
    echo ""                            >> $varFileEntry
    echo "_${varDate} -- ${varTime}_"  >> $varFileEntry
    echo ""                            >> $varFileEntry
}

## ==============================================================================
##
##  Processing
##
## ==============================================================================

##_______________________________________________________________________________
## Get the title for the entry

printf "[$varDate - $varTime] ? ";
read varTitle

##_______________________________________________________________________________
## Create skeleton of file for new entry

echo ""
echo " -> Creating new blog entry ..."
echo ""

writeHeaderWebgen

##_______________________________________________________________________________
## Create the main body of the new blog entry

$varEditor $varFileTemp

## ... and append it to the previously created header segment

cat $varFileTemp >> $varFileWebgen

##_______________________________________________________________________________
## Post-editing cleanup of the directory; remove backup files created by emacs

rm -f $var_dirYear/*~
rm -f $var_dirMonth/*~
rm -rf $varFileTemp
rm -rf $varFileTemp~

##_______________________________________________________________________________
## Update index files

## Change into the root directory for the sources of the blog pages ...
cd $varWebgenBlog

## ... and run the index generation script on the directory with the previously
##     created entry.
$varWebgenRoot/src/code/scripts/blog_index $varYear
